//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplar
    {
        public int KitapId { get; set; }
        public string Tur { get; set; }
        public string Ad { get; set; }
        public string Yazar { get; set; }
        public Nullable<System.DateTime> YayinTarihi { get; set; }
        public string Yayinci { get; set; }
        public string Dil { get; set; }
        public string SayfaSayisi { get; set; }
    }
}
